import { describe, expect, it } from "vitest";
import { ARCS, PROTAGONISTS, SECONDARY, PETS, VILLAINS, type Draft } from "../data";
import { AUCTION_IPS, generateAuction, initIPMarket, licensedRevenue, migrateIPMarket, placePlayerBid, tickIPMarket } from "../ip";
import { arcLockReason, initialRun, migrateRun, startProject } from "../state";
import { applyIntervention } from "../spending";

const licensedDraft = (ipId=AUCTION_IPS[0].id):Draft => { const ip=AUCTION_IPS.find(x=>x.id===ipId)!; return {title:ip.title,medium:"fanweb",budget:"indie",scope:"short",slot:"web",animeType:ip.animeType,genres:ip.genreTags.slice(0,2),audience:ip.audience,protag:PROTAGONISTS[0].id,protagName:ip.characters[0].name,secondary:SECONDARY[0].id,pet:PETS[0].id,villain:VILLAINS[0].id,arcs:["hook","lore","finale"],sliders:[50,50,50],season:1,licensedIpId:ipId,licensedArcId:ip.availableArcs[0].id,licensedCharacters:ip.characters.map(c=>c.name)}; };

describe("economy and IP expansion",()=>{
 it("migrates legacy careers additively without changing genres or history",()=>{const old=initialRun("Legacy","steady");old.genresUnlocked=["horror","mecha"];old.hallOfFame=[{title:"Old Hit",score:33,genres:["horror"],animeType:"shonen",protag:PROTAGONISTS[0].id,week:3}];delete (old as Partial<typeof old>).ipMarket;const next=migrateRun(old);expect(next.genresUnlocked).toEqual(expect.arrayContaining(["horror","mecha"]));expect(next.hallOfFame[0].title).toBe("Old Hit");expect(next.ipMarket.owned).toEqual({});});
 it("ships 36+ stable, original IP records",()=>{expect(AUCTION_IPS.length).toBeGreaterThanOrEqual(36);expect(new Set(AUCTION_IPS.map(x=>x.id)).size).toBe(AUCTION_IPS.length);expect(AUCTION_IPS.every(x=>x.characters.length>=3&&x.availableArcs.length>=3)).toBe(true);});
 it("assigns immutable poster slots inside the 80-asset contract",()=>{expect(AUCTION_IPS.map(x=>x.posterSlot)).toEqual(AUCTION_IPS.map((_,i)=>i+1));expect(new Set(AUCTION_IPS.map(x=>x.posterAsset)).size).toBe(AUCTION_IPS.length);expect(AUCTION_IPS.every(x=>/^\/auction-ip\/poster_\d{3}\.webp$/.test(x.posterAsset)&&x.posterSlot<=80)).toBe(true);});
 it("spans vulnerable early, pressured mid and premium late affordability bands",()=>{const bids=AUCTION_IPS.map(x=>x.minimumBid);expect(Math.min(...bids)).toBeLessThanOrEqual(90_000);expect(AUCTION_IPS.filter(x=>x.rarity==="recognised"||x.rarity==="premium").some(x=>x.minimumBid>=250_000)).toBe(true);expect(AUCTION_IPS.filter(x=>x.rarity==="legendary").every(x=>x.rightsBaseValue>=1_000_000)).toBe(true);});
 it("generates auctions without already-owned or duplicate active IP",()=>{const run=initialRun("A","steady");const blocked=AUCTION_IPS[0].id;run.ipMarket.owned[blocked]={ipId:blocked,acquiredWeek:0,expiresWeek:99,purchasePrice:1,royaltyRate:.1,ownershipShare:.3,sequelRights:false,merchRights:false,internationalRights:false,adaptations:0,bestScore:0,discoveredArcs:[]};const first=generateAuction({...run,ipMarket:run.ipMarket},()=>0)!;expect(first.ipId).not.toBe(blocked);run.ipMarket.auctions=[first];const second=generateAuction({...run,ipMarket:run.ipMarket},()=>0)!;expect(second.ipId).not.toBe(first.ipId);});
 it("validates bids and resolves ownership on expiry",()=>{const ip=AUCTION_IPS[0];let m=initIPMarket(0);m.auctions=[{id:"a",ipId:ip.id,type:"open",opensWeek:0,closesWeek:1,currentBid:10_000,leadingStudioId:null,playerMaxBid:0,bids:[],appraisalLevel:0,resolved:false,winnerId:null,winningBid:0}];expect(placePlayerBid(m,"a",9_000,99_000)).toBeNull();m=placePlayerBid(m,"a",20_000,99_000)!;const run=initialRun("A","steady");const out=tickIPMarket(m,{week:1,cash:99_000,fans:0,awards:0,bestScore:0,showsMade:0},run.rivalWorld,()=>1);expect(out.market.owned[ip.id]).toBeTruthy();expect(out.cashDelta).toBe(-20_000);expect(out.market.auctions[0].resolved).toBe(true);});
 it("lets stateful rivals outbid a weak player during a live auction",()=>{const ip=AUCTION_IPS[0];const run=initialRun("A","steady");const m=initIPMarket(0);m.auctions=[{id:"a",ipId:ip.id,type:"open",opensWeek:0,closesWeek:4,currentBid:10_000,leadingStudioId:"player",playerMaxBid:10_000,bids:[],appraisalLevel:0,resolved:false,winnerId:null,winningBid:0}];const out=tickIPMarket(m,{week:1,cash:99_000,fans:0,awards:0,bestScore:0,showsMade:0},run.rivalWorld,()=>0);expect(out.market.auctions[0].leadingStudioId).not.toBe("player");expect(out.market.auctions[0].bids[out.market.auctions[0].bids.length-1]?.studioId).not.toBe("player");});
 it("greenlights licensed work without the normal casting route",()=>{const run=initialRun("A","steady");run.cash=1_000_000;const ip=AUCTION_IPS[0];run.ipMarket.owned[ip.id]={ipId:ip.id,acquiredWeek:0,expiresWeek:99,purchasePrice:1,royaltyRate:.1,ownershipShare:.3,sequelRights:false,merchRights:false,internationalRights:false,adaptations:0,bestScore:0,discoveredArcs:[]};const next=startProject(run,licensedDraft(ip.id));expect(next?.projects[0].draft.licensedIpId).toBe(ip.id);expect(next?.projects[0].draft.licensedCharacters?.[0]).toBe(ip.characters[0].name);});
 it("persists a discovered hidden blueprint and exposes its arc to originals",()=>{const arc=ARCS.find(a=>a.id==="bottle_episode")!;const run=initialRun("A","steady");expect(arcLockReason(arc,run)).toContain("Hidden");run.ipMarket=migrateIPMarket({studioArcs:["bottle_episode"]},8);expect(arcLockReason(arc,run)).toBeNull();});
 it("applies a contextual rescue cost and effect only once",()=>{const run=initialRun("A","steady");run.cash=1_000_000;const p=startProject(run,{...licensedDraft(),licensedIpId:undefined,licensedArcId:undefined,licensedCharacters:undefined,title:"Original"})!.projects[0];p.stage="animation";const withP={...run,projects:[p]};const out=applyIntervention(withP,p.id,"animation_pass",()=>1)!;expect(out.cash).toBeLessThan(withP.cash);expect(out.projects[0].points.art).toBeGreaterThan(p.points.art);expect(applyIntervention(out,p.id,"animation_pass",()=>1)).toBeNull();});
 it("calculates royalty and co-production ownership shares deterministically",()=>{expect(licensedRevenue(1_000_000,{royaltyRate:.12,ownershipShare:.3})).toEqual({royalty:120_000,ownershipRevenue:264_000,net:1_144_000});});
});
