import type { Arc, ArcCombo } from "./data";
import { IP_HIDDEN_ARC_SEEDS } from "./ipHiddenArcs";
const general = [["Students Become Soldiers", "narr_mentor timeskip war"], ["An Ordinary Night Matters", "narr_slowburn movienight narr_quiet"], ["The Job Comes Apart", "g30_cr_heistblueprint heist narr_betrayal"], ["Recruits Hold the Line", "bootcamp narr_rivalintro narr_siege"], ["The Missing Perspective", "case directorscut narr_pov"], ["Beyond Familiar Faces", "fanservice narr_quiet confession"], ["Worlds Answer Together", "crossover mega finale"], ["Recognition Earned", "live awardpush finale"], ["Orders or Loyalty", "narr_politics guildwar v3_brokenstandard"], ["A Home Worth Growing", "narr_foundfamily expansion v3_sharedtable"], ["Rivals Share the Stage", "narr_rivalintro idolfest live"], ["Everyone Is a Suspect", "case bottle_episode narr_villainreveal"], ["Bring Them Back", "narr_journey underworld_journey narr_rescue"], ["Living Another Life", "body_swap narr_quiet confession"], ["The Hero Behind the Mask", "narr_secretid corruption narr_villainreveal"], ["Together After Goodbye", "narr_foundfamily graduation confession"], ["One World Must Be Saved", "lore multiverse narr_sacrifice"], ["How We Reached This Moment", "narr_mediasres narr_pov twist"], ["Discovery Was the Trap", "narr_explore lore narr_falsewin"], ["Care Beyond Control", "g30_mt_firstbond g30_mt_runawayapex g30_mt_releasechoice"], ["Family Becomes an Empire", "g30_cr_familydebt g30_cr_turfwar vg_nocleanhands"], ["Beneath Forbidden Knowledge", "g30_ch_forbiddentext g30_ch_belowexpedition g30_ch_geometrybreaks"], ["Honour Without Ownership", "g30_ar_caravanoath g30_ar_desertduel g30_ar_masterlesslamp"], ["A Meal Beyond Competition", "cookingbattle v3_sharedtable finale"], ["Strength Without Revenge", "montage v3_crossroadsduel redemption"], ["The Rival Sets the Pace", "narr_rivalintro montage grandprix"], ["Shelter Before the Crossing", "v3_winterharbour vg_lastgoodmeal v3_chartedescape"], ["The Hunter Changes Sides", "vg_hunterswarrant g30_cr_undercoverbadge vg_crimsontruce"], ["Save the Creature Save the City", "g30_kj_hatchling g30_kj_evacline g30_x_colossusbond"], ["Love Without the Bargain", "g30_ar_djinnbargain narr_secretid confession"]];
const loops = [["Learn From Failure", "ip_arc_026 montage tournament"], ["Save Them This Time", "ip_arc_026 narr_rescue finale"], ["The Repeated Crime", "case ip_arc_026 narr_villainreveal"], ["Choose a Different Life", "corruption ip_arc_026 redemption"], ["An Ordinary Day Is Enough", "ip_arc_026 narr_quiet graduation"], ["Prevent the Betrayal", "ip_arc_026 v3_doubleagent narr_betrayal"], ["Escape the Same Disaster", "ip_arc_026 narr_survival v3_chartedescape"], ["A Promise Across Time", "v3_swornoath ip_arc_026 narr_sacrifice"], ["The Second Heist", "g30_cr_heistblueprint ip_arc_026 heist"], ["History Refuses to Change", "ip_arc_026 narr_falsewin twist"]];
const families = [["Underdog Championship", "narr_rivalintro narr_mentor montage tournament v3_duelwithoutblades finale"], ["Defenders Become Family", "narr_foundfamily bootcamp narr_politics narr_siege narr_sacrifice finale"], ["Perfect Job Falls Apart", "g30_cr_heistblueprint v3_silententry heist narr_betrayal v3_chartedescape finale"], ["Life Beyond Revenge", "origin narr_revenge v3_crossroadsduel narr_quiet redemption finale"], ["Truth Has Many Witnesses", "hook case narr_pov directorscut narr_villainreveal twist"], ["Family Breaks the Curse", "narr_slowburn narr_foundfamily narr_secretid transformation narr_quiet confession"], ["A Race Worth Returning To", "narr_rivalintro montage grandprix timeskip v3_duelwithoutblades finale"], ["The Last Safe Harbour", "narr_explore v3_winterharbour vg_lastgoodmeal narr_siege v3_chartedescape graduation"], ["A Meal That Changes the House", "narr_mentor cookingbattle narr_rivalintro v3_sharedtable narr_quiet confession"], ["The Hunter and the Hunted", "vg_hunterswarrant ghosthunt case vg_falseheartbeat vg_crimsontruce redemption"], ["The City and Its Creature", "g30_kj_firstsiren g30_kj_ecology g30_kj_hatchling g30_kj_evacline g30_x_colossusbond finale"], ["The Bargain Without a Master", "g30_ar_caravanoath g30_ar_djinnbargain g30_ar_lostcity g30_ar_desertduel g30_ar_masterlesslamp narr_quiet"], ["The Crown Costs Everything", "narr_mentor ip_arc_101 narr_politics narr_betrayal v3_brokenstandard finale"], ["Liberation Beyond Victory", "narr_foundfamily ip_arc_102 narr_siege narr_falsewin narr_sacrifice finale"], ["The Band Finds Its Voice", "narr_rivalintro ip_arc_103 narr_quiet idolfest live graduation"], ["Who Owns Your Mind", "narr_secretid g30_cr_heistblueprint ip_arc_108 narr_betrayal ip_arc_135 finale"], ["Partner Not Weapon", "g30_mt_firstbond g30_mt_rivaltamer ip_arc_114 g30_mt_evolutioncrisis g30_mt_releasechoice finale"], ["The Expedition Changes Everyone", "narr_explore ip_arc_105 lore g30_ch_geometrybreaks g30_ch_sanitybargain v3_chartedescape"], ["Blood Contract Reckoning", "narr_journey ip_arc_115 case narr_villainreveal v3_duelwithoutblades redemption"], ["Until the Sun Returns", "hook ip_arc_130 vg_daybreaksiege narr_survival narr_sacrifice v3_chartedescape"], ["The Troupe Becomes Home", "narr_slowburn ip_arc_129 vg_midnightencore narr_secretid narr_quiet narr_foundfamily"], ["A Settlement Beyond the Map", "narr_explore ip_arc_137 lore expansion v3_sharedtable graduation"], ["The Record of a Disaster", "hook ip_arc_121 narr_pov g30_kj_ecology twist v3_lastbroadcast"], ["The Road Through the Apocalypse", "narr_foundfamily ip_arc_136 ghosthunt narr_rescue narr_sacrifice finale"]];
const tier = (n: number) => ({ q: n === 2 ? 3 : n === 3 ? 5 : n === 4 ? 8 : n === 5 ? 10 : 12, f: n === 2 ? .025 : n === 3 ? .035 : n === 4 ? .045 : n === 5 ? .055 : .065 });
export function expandedArcCombos(arcs: Arc[]): ArcCombo[] {
 const out: ArcCombo[] = [...general, ...loops].map(([name, ids], i) => ({ id: `exp_structure_${i}`, name, arcs: ids.split(" "), ordered: true, ...tier(3) }));
 for (const seed of IP_HIDDEN_ARC_SEEDS) {
  const premise = `${seed.name} ${seed.desc}`.toLowerCase();
  const path = /heist|theft|criminal|crime|syndicate/.test(premise) ? ["g30_cr_heistblueprint", "narr_betrayal", "v3_chartedescape"]
   : /case|investigat|mystery|testimony|clue|memory/.test(premise) ? ["case", "narr_pov", "twist"]
   : /band|music|concert|perform|dance|cabaret|duet|tour bus/.test(premise) ? ["narr_quiet", "idolfest", "live"]
   : /league|tournament|compet|eliminat|examination/.test(premise) ? ["narr_rivalintro", "montage", "tournament"]
   : /rescue|recover|escape|stranded/.test(premise) ? ["narr_foundfamily", "narr_rescue", "v3_chartedescape"]
   : /war|siege|army|military|liberat|revolution|fleet|campaign/.test(premise) ? ["narr_politics", "narr_siege", "v3_brokenstandard"]
   : /love|romance|relationship|intimacy|date|family|workplace/.test(premise) ? ["narr_slowburn", "narr_quiet", "confession"]
   : /creature|partner|familiar|evolution|beast/.test(premise) ? ["g30_mt_firstbond", "g30_mt_evolutioncrisis", "g30_mt_releasechoice"]
   : /horror|forbidden|dream|contaminat|cosmic/.test(premise) ? ["narr_explore", "g30_ch_sanitybargain", "twist"]
   : ["narr_journey", "lore", "finale"];
  out.push({id:`exp_${seed.id}_development`,name:`${seed.name}: Development`,arcs:[path[0],seed.id,path[2]],ordered:true,...tier(3),family:`ip_${seed.id}`});
  out.push({id:`exp_${seed.id}_resolution`,name:`${seed.name}: Resolution`,arcs:[path[0],seed.id,path[1],path[2]],ordered:true,...tier(4),family:`ip_${seed.id}`});
 }
 families.forEach(([name, ids], i) => {
  const six=ids.split(" ");
  const fourIndices=[[0,2,3,5],[0,1,3,5],[0,2,3,4],[1,2,4,5],[1,2,4,5],[1,2,3,5],[0,1,2,5],[0,1,3,4],[0,1,3,5],[0,2,3,4],[0,2,3,4],[0,1,2,4],[1,2,4,5],[0,1,2,5],[1,2,4,5],[0,2,4,5],[0,2,3,4],[0,1,3,5],[0,1,2,5],[0,1,3,5],[1,2,4,5],[0,1,3,5],[0,1,2,4],[0,1,3,5]][i];
  const fiveIndices=[...fourIndices];
  const extra=[0,1,2,3,4,5].find(index=>!fiveIndices.includes(index)&&index<Math.max(...fourIndices))!;
  fiveIndices.push(extra);fiveIndices.sort((a,b)=>a-b);
  for (const n of [4,5,6]) {
   const selected=n===4 ? fourIndices.map(index=>six[index]) : n===5 ? fiveIndices.map(index=>six[index]) : six;
   out.push({id:`exp_family_${i}_${n}`,name:`${name} (${n} arcs)`,arcs:selected,ordered:true,family:`complete_${i}`,...tier(n)});
  }
 });
 for (const combo of out) if (combo.arcs.some(id=>!arcs.some(a=>a.id===id))) throw new Error(`Unknown beat in ${combo.id}`);
 return out;
}
