// Generated from docs/USER_AUCTION_IP_CATALOG.csv. Keep stable slot/id ordering.
export const USER_IP_CATALOG = [
  {"slot":1,"id":"ip_001","title":"Crystal Quest: Four Hearts, One Tomorrow","sourceType":"jrpg","animeType":"shonen","genres":["fantasy","mythology"],"hiddenArcId":"ip_arc_001","posterAsset":"/auction-ip/poster_001.webp"},
  {"slot":2,"id":"ip_002","title":"Lifestream Rebellion: A Brighter Tomorrow","sourceType":"jrpg","animeType":"shonen","genres":["cyber","fantasy"],"hiddenArcId":"ip_arc_002","posterAsset":"/auction-ip/poster_002.webp"},
  {"slot":3,"id":"ip_003","title":"Relic of the Wild: Kingdom at Dawn","sourceType":"game","animeType":"shonen","genres":["fantasy","mythology"],"hiddenArcId":"ip_arc_003","posterAsset":"/auction-ip/poster_003.webp"},
  {"slot":4,"id":"ip_004","title":"The Flamebound Heir: A Kingdom Endures","sourceType":"jrpg","animeType":"shonen","genres":["fantasy","military"],"hiddenArcId":"ip_arc_004","posterAsset":"/auction-ip/poster_004.webp"},
  {"slot":5,"id":"ip_005","title":"Three Banners Academy","sourceType":"jrpg","animeType":"shojo","genres":["fantasy","military"],"hiddenArcId":"ip_arc_005","posterAsset":"/auction-ip/poster_005.webp"},
  {"slot":6,"id":"ip_006","title":"The Black Ledger: A Deadly Mind Game","sourceType":"manga","animeType":"shonen","genres":["mystery","supernatural"],"hiddenArcId":"ip_arc_006","posterAsset":"/auction-ip/poster_006.webp"},
  {"slot":7,"id":"ip_007","title":"Solar Fist: A Brighter World","sourceType":"manga","animeType":"shonen","genres":["martial","supernatural"],"hiddenArcId":"ip_arc_007","posterAsset":"/auction-ip/poster_007.webp"},
  {"slot":8,"id":"ip_008","title":"Star Dragon Trail: Beyond Tomorrow","sourceType":"tv","animeType":"shonen","genres":["martial","space"],"hiddenArcId":"ip_arc_008","posterAsset":"/auction-ip/poster_008.webp"},
  {"slot":9,"id":"ip_009","title":"Brotherhood of Brass: Alchemical Dawn","sourceType":"manga","animeType":"shonen","genres":["magical","military"],"hiddenArcId":"ip_arc_009","posterAsset":"/auction-ip/poster_009.webp"},
  {"slot":10,"id":"ip_010","title":"Infernal Requiem: A Brighter Hell","sourceType":"game","animeType":"shonen","genres":["supernatural","horror"],"hiddenArcId":"ip_arc_010","posterAsset":"/auction-ip/poster_010.webp"},
  {"slot":11,"id":"ip_011","title":"The Nameless Smile","sourceType":"manga","animeType":"shojo","genres":["mystery","horror"],"hiddenArcId":"ip_arc_011","posterAsset":"/auction-ip/poster_011.webp"},
  {"slot":12,"id":"ip_012","title":"Covenant of Midnight","sourceType":"visual_novel","animeType":"shonen","genres":["magical","supernatural"],"hiddenArcId":"ip_arc_012","posterAsset":"/auction-ip/poster_012.webp"},
  {"slot":13,"id":"ip_013","title":"Battle School Orion","sourceType":"novel","animeType":"shonen","genres":["space","military"],"hiddenArcId":"ip_arc_013","posterAsset":"/auction-ip/poster_013.webp"},
  {"slot":14,"id":"ip_014","title":"Rising Eleven: From Streets to Stardom","sourceType":"game","animeType":"shonen","genres":["sports","slice"],"hiddenArcId":"ip_arc_014","posterAsset":"/auction-ip/poster_014.webp"},
  {"slot":15,"id":"ip_015","title":"Iron Howlers: Stormfront Mechs","sourceType":"game","animeType":"shonen","genres":["mecha","military"],"hiddenArcId":"ip_arc_015","posterAsset":"/auction-ip/poster_015.webp"},
  {"slot":16,"id":"ip_016","title":"Ash Throne Legion","sourceType":"tabletop","animeType":"shonen","genres":["space","mecha"],"hiddenArcId":"ip_arc_016","posterAsset":"/auction-ip/poster_016.webp"},
  {"slot":17,"id":"ip_017","title":"Starfall Rebellion","sourceType":"film","animeType":"shonen","genres":["space","mythology"],"hiddenArcId":"ip_arc_017","posterAsset":"/auction-ip/poster_017.webp"},
  {"slot":18,"id":"ip_018","title":"Moonlit Maze","sourceType":"film","animeType":"shojo","genres":["isekai","magical"],"hiddenArcId":"ip_arc_018","posterAsset":"/auction-ip/poster_018.webp"},
  {"slot":19,"id":"ip_019","title":"Wildspark Quest","sourceType":"game","animeType":"shojo","genres":["magical","sports"],"hiddenArcId":"ip_arc_019","posterAsset":"/auction-ip/poster_019.webp"},
  {"slot":20,"id":"ip_020","title":"Cyber Crests","sourceType":"tv","animeType":"shonen","genres":["cyber","isekai"],"hiddenArcId":"ip_arc_020","posterAsset":"/auction-ip/poster_020.webp"},
  {"slot":21,"id":"ip_021","title":"Soul Tide","sourceType":"manga","animeType":"shonen","genres":["supernatural","martial"],"hiddenArcId":"ip_arc_021","posterAsset":"/auction-ip/poster_021.webp"},
  {"slot":22,"id":"ip_022","title":"Hidden Storm","sourceType":"manga","animeType":"shonen","genres":["shinobi","martial"],"hiddenArcId":"ip_arc_022","posterAsset":"/auction-ip/poster_022.webp"},
  {"slot":23,"id":"ip_023","title":"Grand Horizon Voyage","sourceType":"manga","animeType":"shonen","genres":["pirate","martial"],"hiddenArcId":"ip_arc_023","posterAsset":"/auction-ip/poster_023.webp"},
  {"slot":24,"id":"ip_024","title":"Tidebreak Champions","sourceType":"game","animeType":"shonen","genres":["sports","fantasy"],"hiddenArcId":"ip_arc_024","posterAsset":"/auction-ip/poster_024.webp"},
  {"slot":25,"id":"ip_025","title":"War of Three Banners","sourceType":"novel","animeType":"shonen","genres":["military","martial"],"hiddenArcId":"ip_arc_025","posterAsset":"/auction-ip/poster_025.webp"},
  {"slot":26,"id":"ip_026","title":"A Pocketful of Tomorrows","sourceType":"film","animeType":"shojo","genres":["romance","supernatural"],"hiddenArcId":"ip_arc_026","posterAsset":"/auction-ip/poster_026.webp"},
  {"slot":27,"id":"ip_027","title":"Ashfall Dominion","sourceType":"film","animeType":"shonen","genres":["survival","horror"],"hiddenArcId":"ip_arc_027","posterAsset":"/auction-ip/poster_027.webp"},
  {"slot":28,"id":"ip_028","title":"Northern Oath","sourceType":"manga","animeType":"shonen","genres":["nordic","military"],"hiddenArcId":"ip_arc_028","posterAsset":"/auction-ip/poster_028.webp"},
  {"slot":29,"id":"ip_029","title":"Snowbound Hunger","sourceType":"film","animeType":"shojo","genres":["nordic","horror"],"hiddenArcId":"ip_arc_029","posterAsset":"/auction-ip/poster_029.webp"},
  {"slot":30,"id":"ip_030","title":"Radio Rebels","sourceType":"film","animeType":"shojo","genres":["idol","comedy"],"hiddenArcId":"ip_arc_030","posterAsset":"/auction-ip/poster_030.webp"},
  {"slot":31,"id":"ip_031","title":"Midnight Soul Run","sourceType":"film","animeType":"shojo","genres":["idol","comedy"],"hiddenArcId":"ip_arc_031","posterAsset":"/auction-ip/poster_031.webp"},
  {"slot":32,"id":"ip_032","title":"The Seventh Trace","sourceType":"film","animeType":"shonen","genres":["mystery","horror"],"hiddenArcId":"ip_arc_032","posterAsset":"/auction-ip/poster_032.webp"},
  {"slot":33,"id":"ip_033","title":"Lineup of Shadows","sourceType":"film","animeType":"shonen","genres":["mystery","horror"],"hiddenArcId":"ip_arc_033","posterAsset":"/auction-ip/poster_033.webp"},
  {"slot":34,"id":"ip_034","title":"Velvet Appetite","sourceType":"novel","animeType":"shojo","genres":["horror","mystery"],"hiddenArcId":"ip_arc_034","posterAsset":"/auction-ip/poster_034.webp"},
  {"slot":35,"id":"ip_035","title":"Crestfall Dominion","sourceType":"light_novel","animeType":"shonen","genres":["fantasy","military"],"hiddenArcId":"ip_arc_035","posterAsset":"/auction-ip/poster_035.webp"},
  {"slot":36,"id":"ip_036","title":"The Hidden Striker","sourceType":"film","animeType":"shojo","genres":["romance","comedy"],"hiddenArcId":"ip_arc_036","posterAsset":"/auction-ip/poster_036.webp"},
  {"slot":37,"id":"ip_037","title":"The Final Ronin","sourceType":"film","animeType":"shonen","genres":["samurai","martial"],"hiddenArcId":"ip_arc_037","posterAsset":"/auction-ip/poster_037.webp"},
  {"slot":38,"id":"ip_038","title":"Retro Newsroom","sourceType":"film","animeType":"shojo","genres":["comedy","slice"],"hiddenArcId":"ip_arc_038","posterAsset":"/auction-ip/poster_038.webp"},
  {"slot":39,"id":"ip_039","title":"The Devourer Queen","sourceType":"comic","animeType":"shojo","genres":["fantasy","horror"],"hiddenArcId":"ip_arc_039","posterAsset":"/auction-ip/poster_039.webp"},
  {"slot":40,"id":"ip_040","title":"Awakened","sourceType":"tv","animeType":"shojo","genres":["supernatural","mystery"],"hiddenArcId":"ip_arc_040","posterAsset":"/auction-ip/poster_040.webp"},
  {"slot":41,"id":"ip_041","title":"Beyond the Veil","sourceType":"tv","animeType":"shonen","genres":["supernatural","horror"],"hiddenArcId":"ip_arc_041","posterAsset":"/auction-ip/poster_041.webp"},
  {"slot":42,"id":"ip_042","title":"Phantom Arsenal","sourceType":"game","animeType":"shonen","genres":["military","cyber"],"hiddenArcId":"ip_arc_042","posterAsset":"/auction-ip/poster_042.webp"},
  {"slot":43,"id":"ip_043","title":"Velvet Shade","sourceType":"tv","animeType":"shojo","genres":["idol","comedy"],"hiddenArcId":"ip_arc_043","posterAsset":"/auction-ip/poster_043.webp"},
  {"slot":44,"id":"ip_044","title":"Whisper Society","sourceType":"tv","animeType":"shojo","genres":["romance","mystery"],"hiddenArcId":"ip_arc_044","posterAsset":"/auction-ip/poster_044.webp"},
  {"slot":45,"id":"ip_045","title":"Golden Coast","sourceType":"tv","animeType":"shojo","genres":["romance","slice"],"hiddenArcId":"ip_arc_045","posterAsset":"/auction-ip/poster_045.webp"},
  {"slot":46,"id":"ip_046","title":"Crown of Embers","sourceType":"tv","animeType":"shojo","genres":["fantasy","military"],"hiddenArcId":"ip_arc_046","posterAsset":"/auction-ip/poster_046.webp"},
  {"slot":47,"id":"ip_047","title":"Wheel of Ages","sourceType":"novel","animeType":"shojo","genres":["fantasy","mythology"],"hiddenArcId":"ip_arc_047","posterAsset":"/auction-ip/poster_047.webp"},
  {"slot":48,"id":"ip_048","title":"Rogue Rhythm Ronin","sourceType":"tv","animeType":"shonen","genres":["samurai","martial"],"hiddenArcId":"ip_arc_048","posterAsset":"/auction-ip/poster_048.webp"},
  {"slot":49,"id":"ip_049","title":"Starlight Outlaws","sourceType":"tv","animeType":"shonen","genres":["space","cyber"],"hiddenArcId":"ip_arc_049","posterAsset":"/auction-ip/poster_049.webp"},
  {"slot":50,"id":"ip_050","title":"The Black Spire","sourceType":"novel","animeType":"shonen","genres":["fantasy","horror"],"hiddenArcId":"ip_arc_050","posterAsset":"/auction-ip/poster_050.webp"},
  {"slot":51,"id":"ip_051","title":"Rising Tempest","sourceType":"game","animeType":"shonen","genres":["cyber","mecha"],"hiddenArcId":"ip_arc_051","posterAsset":"/auction-ip/poster_051.webp"},
  {"slot":52,"id":"ip_052","title":"Sunwheel Exiles","sourceType":"game","animeType":"shojo","genres":["cyber","survival"],"hiddenArcId":"ip_arc_052","posterAsset":"/auction-ip/poster_052.webp"},
  {"slot":53,"id":"ip_053","title":"Whisper Keyhouse","sourceType":"comic","animeType":"shojo","genres":["supernatural","mystery"],"hiddenArcId":"ip_arc_053","posterAsset":"/auction-ip/poster_053.webp"},
  {"slot":54,"id":"ip_054","title":"Thornwall Abbey","sourceType":"novel","animeType":"shojo","genres":["fantasy","military"],"hiddenArcId":"ip_arc_054","posterAsset":"/auction-ip/poster_054.webp"},
  {"slot":55,"id":"ip_055","title":"Dungeon Banquet","sourceType":"manga","animeType":"shojo","genres":["cooking","fantasy"],"hiddenArcId":"ip_arc_055","posterAsset":"/auction-ip/poster_055.webp"},
  {"slot":56,"id":"ip_056","title":"Inferno Kitchen","sourceType":"tv","animeType":"shonen","genres":["cooking","survival"],"hiddenArcId":"ip_arc_056","posterAsset":"/auction-ip/poster_056.webp"},
  {"slot":57,"id":"ip_057","title":"Feast Challenger","sourceType":"tv","animeType":"shonen","genres":["cooking","comedy"],"hiddenArcId":"ip_arc_057","posterAsset":"/auction-ip/poster_057.webp"},
  {"slot":58,"id":"ip_058","title":"Scarlet Circle","sourceType":"tv","animeType":"shonen","genres":["survival","mystery"],"hiddenArcId":"ip_arc_058","posterAsset":"/auction-ip/poster_058.webp"},
  {"slot":59,"id":"ip_059","title":"Target Homeroom","sourceType":"manga","animeType":"shonen","genres":["comedy","martial"],"hiddenArcId":"ip_arc_059","posterAsset":"/auction-ip/poster_059.webp"},
  {"slot":60,"id":"ip_060","title":"Aether Online","sourceType":"light_novel","animeType":"shonen","genres":["isekai","cyber"],"hiddenArcId":"ip_arc_060","posterAsset":"/auction-ip/poster_060.webp"},
  {"slot":61,"id":"ip_061","title":"Spiral Tide","sourceType":"jrpg","animeType":"shojo","genres":["fantasy","romance"],"hiddenArcId":"ip_arc_061","posterAsset":"/auction-ip/poster_061.webp"},
  {"slot":62,"id":"ip_062","title":"Black File","sourceType":"film","animeType":"shonen","genres":["space","comedy"],"hiddenArcId":"ip_arc_062","posterAsset":"/auction-ip/poster_062.webp"},
  {"slot":63,"id":"ip_063","title":"Plastic Kingdom","sourceType":"film","animeType":"shojo","genres":["comedy","slice"],"hiddenArcId":"ip_arc_063","posterAsset":"/auction-ip/poster_063.webp"},
  {"slot":64,"id":"ip_064","title":"Poison Petals","sourceType":"film","animeType":"shojo","genres":["comedy","horror"],"hiddenArcId":"ip_arc_064","posterAsset":"/auction-ip/poster_064.webp"},
  {"slot":65,"id":"ip_065","title":"Winter Maw","sourceType":"film","animeType":"shonen","genres":["survival","nordic"],"hiddenArcId":"ip_arc_065","posterAsset":"/auction-ip/poster_065.webp"},
  {"slot":66,"id":"ip_066","title":"Thousand Bad Ends","sourceType":"film","animeType":"shojo","genres":["comedy","martial"],"hiddenArcId":"ip_arc_066","posterAsset":"/auction-ip/poster_066.webp"},
  {"slot":67,"id":"ip_067","title":"Starspark Stunt","sourceType":"film","animeType":"shojo","genres":["comedy","sports"],"hiddenArcId":"ip_arc_067","posterAsset":"/auction-ip/poster_067.webp"},
  {"slot":68,"id":"ip_068","title":"Shadowmaw","sourceType":"novel","animeType":"shonen","genres":["horror","supernatural"],"hiddenArcId":"ip_arc_068","posterAsset":"/auction-ip/poster_068.webp"},
  {"slot":69,"id":"ip_069","title":"Stormheart Castle","sourceType":"novel","animeType":"shojo","genres":["magical","romance"],"hiddenArcId":"ip_arc_069","posterAsset":"/auction-ip/poster_069.webp"},
  {"slot":70,"id":"ip_070","title":"Sword and Rose","sourceType":"film","animeType":"shojo","genres":["romance","comedy"],"hiddenArcId":"ip_arc_070","posterAsset":"/auction-ip/poster_070.webp"},
  {"slot":71,"id":"ip_071","title":"Lionheart War","sourceType":"jrpg","animeType":"shonen","genres":["fantasy","military"],"hiddenArcId":"ip_arc_071","posterAsset":"/auction-ip/poster_071.webp"},
  {"slot":72,"id":"ip_072","title":"The Obsidian Archive","sourceType":"audio_drama","animeType":"shojo","genres":["mystery","horror"],"hiddenArcId":"ip_arc_072","posterAsset":"/auction-ip/poster_072.webp"},
  {"slot":73,"id":"ip_073","title":"500 Days of Sunlight","sourceType":"film","animeType":"shojo","genres":["romance","slice"],"hiddenArcId":"ip_arc_073","posterAsset":"/auction-ip/poster_073.webp"},
  {"slot":74,"id":"ip_074","title":"Moonstake Hunter","sourceType":"tv","animeType":"shojo","genres":["supernatural","martial"],"hiddenArcId":"ip_arc_074","posterAsset":"/auction-ip/poster_074.webp"},
  {"slot":75,"id":"ip_075","title":"Parasol Academy","sourceType":"comic","animeType":"shojo","genres":["supernatural","mystery"],"hiddenArcId":"ip_arc_075","posterAsset":"/auction-ip/poster_075.webp"},
  {"slot":76,"id":"ip_076","title":"Starbound Slumber","sourceType":"film","animeType":"shojo","genres":["romance","space"],"hiddenArcId":"ip_arc_076","posterAsset":"/auction-ip/poster_076.webp"},
  {"slot":77,"id":"ip_077","title":"Silicon Heart","sourceType":"film","animeType":"shojo","genres":["romance","cyber"],"hiddenArcId":"ip_arc_077","posterAsset":"/auction-ip/poster_077.webp"},
  {"slot":78,"id":"ip_078","title":"The Last Letter","sourceType":"film","animeType":"shojo","genres":["romance","slice"],"hiddenArcId":"ip_arc_078","posterAsset":"/auction-ip/poster_078.webp"},
  {"slot":79,"id":"ip_079","title":"Hidden Dragon Moon","sourceType":"film","animeType":"shojo","genres":["martial","romance"],"hiddenArcId":"ip_arc_079","posterAsset":"/auction-ip/poster_079.webp"},
  {"slot":80,"id":"ip_080","title":"Bullet Requiem","sourceType":"game","animeType":"shonen","genres":["mystery","cyber"],"hiddenArcId":"ip_arc_080","posterAsset":"/auction-ip/poster_080.webp"},
  {"slot":81,"id":"ip_081","title":"Skyshard Chronicle","sourceType":"jrpg","animeType":"shojo","genres":["fantasy","magical"],"hiddenArcId":"ip_arc_081","posterAsset":"/auction-ip/poster_081.webp"},
  {"slot":82,"id":"ip_082","title":"Bramble & Beak","sourceType":"game","animeType":"shojo","genres":["comedy","fantasy"],"hiddenArcId":"ip_arc_082","posterAsset":"/auction-ip/poster_082.webp"},
  {"slot":83,"id":"ip_083","title":"Scarlet Tail","sourceType":"game","animeType":"shonen","genres":["comedy","survival"],"hiddenArcId":"ip_arc_083","posterAsset":"/auction-ip/poster_083.webp"},
  {"slot":84,"id":"ip_084","title":"Mindgate Zero","sourceType":"game","animeType":"shonen","genres":["supernatural","military"],"hiddenArcId":"ip_arc_084","posterAsset":"/auction-ip/poster_084.webp"},
  {"slot":85,"id":"ip_085","title":"Sea of the Second Sun","sourceType":"film","animeType":"shojo","genres":["survival","mythology"],"hiddenArcId":"ip_arc_085","posterAsset":"/auction-ip/poster_085.webp"},
  {"slot":86,"id":"ip_086","title":"Ashen Mile","sourceType":"novel","animeType":"shojo","genres":["survival","horror"],"hiddenArcId":"ip_arc_086","posterAsset":"/auction-ip/poster_086.webp"},
  {"slot":87,"id":"ip_087","title":"Tideborn Drift","sourceType":"film","animeType":"shonen","genres":["pirate","survival"],"hiddenArcId":"ip_arc_087","posterAsset":"/auction-ip/poster_087.webp"},
  {"slot":88,"id":"ip_088","title":"Townlight Rhythm","sourceType":"film","animeType":"shojo","genres":["romance","idol"],"hiddenArcId":"ip_arc_088","posterAsset":"/auction-ip/poster_088.webp"},
  {"slot":89,"id":"ip_089","title":"Autumn Chalkheart","sourceType":"film","animeType":"shojo","genres":["slice","romance"],"hiddenArcId":"ip_arc_089","posterAsset":"/auction-ip/poster_089.webp"},
  {"slot":90,"id":"ip_090","title":"Paper Constellations","sourceType":"film","animeType":"shojo","genres":["slice","comedy"],"hiddenArcId":"ip_arc_090","posterAsset":"/auction-ip/poster_090.webp"},
  {"slot":91,"id":"ip_091","title":"Golden Whistle","sourceType":"tv","animeType":"shojo","genres":["sports","slice"],"hiddenArcId":"ip_arc_091","posterAsset":"/auction-ip/poster_091.webp"},
  {"slot":92,"id":"ip_092","title":"Primate Panic","sourceType":"game","animeType":"shojo","genres":["comedy","cyber"],"hiddenArcId":"ip_arc_092","posterAsset":"/auction-ip/poster_092.webp"},
  {"slot":93,"id":"ip_093","title":"Ashfall Junction","sourceType":"tv","animeType":"shojo","genres":["survival","military"],"hiddenArcId":"ip_arc_093","posterAsset":"/auction-ip/poster_093.webp"},
  {"slot":94,"id":"ip_094","title":"Smile Trigger","sourceType":"tv","animeType":"shonen","genres":["comedy","supernatural"],"hiddenArcId":"ip_arc_094","posterAsset":"/auction-ip/poster_094.webp"},
  {"slot":95,"id":"ip_095","title":"Wings of Yesterday","sourceType":"film","animeType":"shojo","genres":["supernatural","mystery"],"hiddenArcId":"ip_arc_095","posterAsset":"/auction-ip/poster_095.webp"},
  {"slot":96,"id":"ip_096","title":"Desert Formula","sourceType":"tv","animeType":"shonen","genres":["mystery","survival"],"hiddenArcId":"ip_arc_096","posterAsset":"/auction-ip/poster_096.webp"},
  {"slot":97,"id":"ip_097","title":"The Last Windkeeper","sourceType":"tv","animeType":"shonen","genres":["magical","martial"],"hiddenArcId":"ip_arc_097","posterAsset":"/auction-ip/poster_097.webp"},
  {"slot":98,"id":"ip_098","title":"Aether Divide","sourceType":"tv","animeType":"shojo","genres":["cyber","magical"],"hiddenArcId":"ip_arc_098","posterAsset":"/auction-ip/poster_098.webp"},
  {"slot":99,"id":"ip_099","title":"Starwind Outlaws","sourceType":"tv","animeType":"shonen","genres":["space","pirate"],"hiddenArcId":"ip_arc_099","posterAsset":"/auction-ip/poster_099.webp"},
  {"slot":100,"id":"ip_100","title":"Pine Veil","sourceType":"tv","animeType":"shojo","genres":["mystery","supernatural"],"hiddenArcId":"ip_arc_100","posterAsset":"/auction-ip/poster_100.webp"},
] as const;
