import { Gavel, SkipForward, X } from "lucide-react";
import { Btn } from "../fx/fx";
import { dismissAuctionPrompt, genreLabel, ipById, skipAuctionOpportunity, SOURCE_LABEL, type IPAuction } from "../engine/ip";
import { formatGBPShort } from "../engine/data";
import type { RunState } from "../engine/state";

export default function AuctionForecast({run,setRun,onEnter}:{run:RunState;setRun:(fn:(r:RunState)=>RunState)=>void;onEnter:(id:string)=>void}){
  const id=run.ipMarket.pendingPromptId; const auction=id?run.ipMarket.auctions.find(a=>a.id===id):null; const ip=auction?ipById(auction.ipId):null; if(!auction||!ip)return null;
  const close=()=>setRun(r=>({...r,ipMarket:dismissAuctionPrompt(r.ipMarket,auction.id)}));
  const skip=()=>setRun(r=>({...r,ipMarket:skipAuctionOpportunity(r.ipMarket,auction.id,r.rivalWorld),notices:[...r.notices,`Skipped rights auction: ${ip.title}.`]}));
  const enter=()=>{setRun(r=>({...r,ipMarket:dismissAuctionPrompt(r.ipMarket,auction.id)}));onEnter(auction.id)};
  return <div className="fixed inset-0 z-[95] overflow-y-auto bg-[#151022] px-5 pb-[calc(env(safe-area-inset-bottom,0px)+42px)] pt-[calc(env(safe-area-inset-top,0px)+24px)] text-paper"><div className="mx-auto flex min-h-full max-w-2xl flex-col justify-center"><div className="mb-3 text-center"><div className="text-[10px] font-black tracking-[.45em] text-cyanx">INDUSTRY FORECAST</div><div className="mt-1 font-display text-3xl font-black text-gold">RIGHTS AUCTION ALERT</div><div className="mt-1 text-xs text-paper/45">A rare IP rights room has opened. Auction opportunities can occur at most once per industry year.</div></div><div className="ink-card grid gap-4 p-4 sm:grid-cols-[160px_1fr]"><div className="relative mx-auto aspect-[4/5] w-40 overflow-hidden rounded-xl border border-gold/45 bg-panel2"><img src={ip.posterAsset} alt={`${ip.title} poster`} className="h-full w-full object-cover"/><div className="absolute inset-0 ring-1 ring-inset ring-white/10"/></div><div><div className="font-display text-2xl font-black">{ip.title}</div><div className="mt-1 text-[10px] font-bold tracking-widest text-gold">{SOURCE_LABEL[ip.sourceType].toUpperCase()} · {ip.genreTags.map(genreLabel).join(" / ").toUpperCase()}</div><p className="mt-3 text-sm text-paper/65">{ip.description}</p><div className="mt-4 grid grid-cols-2 gap-2 text-xs"><div className="rounded border border-line bg-panel2 p-2"><span className="text-paper/40">Opening bid</span><br/><b className="text-mint">{formatGBPShort(auction.currentBid)}</b></div><div className="rounded border border-line bg-panel2 p-2"><span className="text-paper/40">Window</span><br/><b>THIS WEEK</b></div><div className="rounded border border-line bg-panel2 p-2"><span className="text-paper/40">Fanbase</span><br/><b>≈{ip.fanbase}k</b></div><div className="rounded border border-line bg-panel2 p-2"><span className="text-paper/40">Prestige</span><br/><b>{ip.prestige}</b></div></div><div className="mt-4 rounded-lg border border-viol/30 bg-viol/5 p-2 text-[10px] text-paper/55"><b className="text-viol">UNKNOWN STORY BLUEPRINT</b> · a strong adaptation can permanently teach your studio this property’s hidden arc.</div></div></div><div className="mt-4 grid gap-2 sm:grid-cols-3"><Btn variant="ghost" onClick={skip}><SkipForward size={14}/>SKIP AUCTION</Btn><Btn variant="ghost" onClick={close}><X size={14}/>RETURN TO GAME</Btn><Btn big variant="gold" onClick={enter}><Gavel size={17}/>ENTER AUCTION</Btn></div></div></div>;
}
