from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
path = ROOT / "game_source/src/components/Office.tsx"
text = path.read_text()

text = text.replace(
    'const [modal, setModal] = useState<null | "projects" | "facilities" | "staff" | "research" | "contracts" | "market" | "relocate" | "hof" | "awards" | "sequels" | "rivals" | "dynasty">(null);',
    'const [modal, setModal] = useState<null | "projects" | "facilities" | "staff" | "research" | "contracts" | "market" | "relocate" | "hof" | "awards" | "sequels" | "rivals" | "dynasty" | "more">(null);'
)

# Runtime crash: this stale identifier was left behind when NEXT WEEK was removed.
text = text.replace('            onSkipWeek={onSkipWeek}\n', '            onRushCrunch={onRushCrunch}\n')

start = text.index('      {/* -------------------------------------------------------- actions */}')
end = text.index('      {/* ticker */}', start)
new_actions = '''      {/* ---------------------------------------------------- compact dock */}\n      <div className="relative z-20 shrink-0 border-t border-line/60 bg-ink/90 px-2 py-1.5 backdrop-blur-md">\n        <div className="mx-auto grid max-w-xl grid-cols-5 gap-1">\n          <Btn\n            variant="primary"\n            className={cn("relative !min-h-0 !px-1.5 !py-1.5 text-[9px] sm:text-[10px]", !projAlerts && !newShowBlocked && "anim-ring")}\n            onClick={() => setModal("projects")}\n          >\n            <KanbanSquare size={15} /> <span className="hidden xs:inline">PROJECTS</span><span className="xs:hidden">WORK</span>\n            <span className="text-[8px] opacity-65">{projActive.length}/{projCap}</span>\n            {projAlerts > 0 && (\n              <span className="absolute -right-1 -top-1 flex h-4 min-w-4 items-center justify-center rounded-full bg-gold px-1 font-display text-[8px] font-extrabold text-ink">{projAlerts}</span>\n            )}\n          </Btn>\n          <Btn\n            variant={newShowBlocked ? "ghost" : "primary"}\n            disabled={!!newShowBlocked}\n            className="!min-h-0 !px-1.5 !py-1.5 text-[9px] sm:text-[10px]"\n            onClick={() => onNewShow()}\n          >\n            <Clapperboard size={15} /> NEW SHOW\n          </Btn>\n          <Btn variant="cyan" className="!min-h-0 !px-1.5 !py-1.5 text-[9px] sm:text-[10px]" onClick={() => setModal("contracts")}>\n            <Briefcase size={15} /> JOBS\n          </Btn>\n          <Btn variant="ghost" className="relative !min-h-0 !px-1.5 !py-1.5 text-[9px] sm:text-[10px]" onClick={() => setModal("staff")}>\n            <Users size={15} /> STAFF\n            {run.staffEvents.length > 0 && (\n              <span className="absolute -right-1 -top-1 flex h-4 min-w-4 items-center justify-center rounded-full bg-gold px-1 font-display text-[8px] font-extrabold text-ink">{run.staffEvents.length}</span>\n            )}\n          </Btn>\n          <Btn variant="ghost" className="relative !min-h-0 !px-1.5 !py-1.5 text-[9px] sm:text-[10px]" onClick={() => setModal("more")}>\n            <Sparkles size={15} /> MORE\n            {(run.commissions.length + run.marketEvents.length + (run.studioEvents?.length ?? 0) > 0 || !!seq) && (\n              <span className="absolute -right-1 -top-1 h-2.5 w-2.5 rounded-full bg-cyanx" />\n            )}\n          </Btn>\n        </div>\n        {fc.cashAfter < 0 && (\n          <div className="mx-auto mt-1 max-w-xl truncate text-center text-[9px] font-bold text-neon">\n            <AlertTriangle size={9} className="mr-1 inline" /> Forecast: ≈{formatGBPShort(fc.cashAfter)} next week — take work or cut costs.\n          </div>\n        )}\n      </div>\n\n'''
text = text[:start] + new_actions + text[end:]

# Make the news ticker a slim status strip instead of another bar-sized row.
text = text.replace(
    '      <div className="relative z-20 border-t border-line/40 bg-panel2/70 py-1.5 backdrop-blur-md">',
    '      <div className="relative z-20 shrink-0 border-t border-line/40 bg-panel2/70 py-0.5 backdrop-blur-md">'
).replace(
    '          <div className="inline-block text-[11px] text-paper/60" style={{ animation: "marquee 46s linear infinite" }}>',
    '          <div className="inline-block text-[9px] text-paper/55" style={{ animation: "marquee 46s linear infinite" }}>'
)

more_modal = '''      {/* ----------------------------------------------------------- MORE */}\n      {modal === "more" && (\n        <Modal title="STUDIO MENU" onClose={() => setModal(null)}>\n          <div className="grid grid-cols-2 gap-2 sm:grid-cols-3">\n            <button className="btn-press ink-card flex items-center gap-2 p-3 text-left" onClick={() => setModal("facilities")}><Hammer size={16} className="text-gold"/><span className="text-xs font-bold">STUDIO ROOMS</span></button>\n            <button className="btn-press ink-card flex items-center gap-2 p-3 text-left" onClick={() => setModal("market")}><BarChart3 size={16} className="text-mint"/><span className="text-xs font-bold">MARKET</span></button>\n            <button className="btn-press ink-card flex items-center gap-2 p-3 text-left" onClick={() => setModal("research")}><FlaskConical size={16} className="text-viol"/><span className="text-xs font-bold">R&amp;D</span></button>\n            {seriesList.length > 0 && <button className="btn-press ink-card flex items-center gap-2 p-3 text-left" onClick={() => setModal("sequels")}><Clapperboard size={16} className="text-gold"/><span className="text-xs font-bold">LIBRARY</span></button>}\n            {nextOffice && <button className="btn-press ink-card flex items-center gap-2 p-3 text-left" onClick={() => setModal("relocate")}><Building2 size={16} className="text-cyanx"/><span className="text-xs font-bold">MOVE STUDIO</span></button>}\n            <button className="btn-press ink-card flex items-center gap-2 p-3 text-left" onClick={() => setModal("awards")}><Award size={16} className="text-gold"/><span className="text-xs font-bold">AWARDS</span></button>\n            <button className="btn-press ink-card flex items-center gap-2 p-3 text-left" onClick={() => setModal("rivals")}><Swords size={16} className="text-cyanx"/><span className="text-xs font-bold">RIVALS</span></button>\n            <button className="btn-press ink-card flex items-center gap-2 p-3 text-left" onClick={() => setModal("hof")}><Trophy size={16} className="text-gold"/><span className="text-xs font-bold">RECORDS</span></button>\n            {run.dynasty && <button className="btn-press ink-card flex items-center gap-2 p-3 text-left" onClick={() => setModal("dynasty")}><Crown size={16} className="text-gold"/><span className="text-xs font-bold">DYNASTY</span></button>}\n          </div>\n          {seq && <Btn variant="gold" className="mt-3 w-full" onClick={() => { setModal(null); onNewShow(run.pendingSequel!); }}><Zap size={15}/> START SEASON {seq.season + 1}</Btn>}\n        </Modal>\n      )}\n\n'''
anchor = '      {/* ------------------------------------------------------- CONTRACTS */}'
text = text.replace(anchor, more_modal + anchor)

path.write_text(text)

# Static regression test catches the exact browser-only failure that Vite transpilation missed.
test = ROOT / "game_source/src/engine/__tests__/office-shell.test.ts"
test.write_text('''import { describe, expect, it } from "vitest";\nimport { readFileSync } from "node:fs";\nimport { fileURLToPath } from "node:url";\nimport { dirname, resolve } from "node:path";\n\nconst here = dirname(fileURLToPath(import.meta.url));\nconst office = readFileSync(resolve(here, "../../components/Office.tsx"), "utf8");\n\ndescribe("office shell regressions", () => {\n  it("does not reference the removed skip-week callback", () => {\n    expect(office).not.toContain("onSkipWeek={onSkipWeek}");\n  });\n  it("wires live rush crunch into the Projects board", () => {\n    expect(office).toContain("onRushCrunch={onRushCrunch}");\n  });\n  it("uses the compact five-action management dock", () => {\n    expect(office).toContain("grid-cols-5");\n    expect(office).toContain('setModal("more")');\n  });\n});\n''')
print("Fixed Projects runtime crash and compacted management dock")
